# Apply manual generated-code fixes after `rexglue init`.
# This script is run by build_release.ps1 (or the build pipeline).

import sys, pathlib, re

def patch_sub_825cd3c0(file_path):
    txt = file_path.read_text(encoding="utf-8")
    old = '''\t// Chain to sub_825CD4B8 (addi r4,r1,80; bl sub_825CDBC8) which\n\t// then chains to sub_825CD4C0 (the loop body). The codegen split\n\t// this function at 0x825CD4B8 but didn't add the chain calls.\n\tsub_825CD4B8(ctx, base);\n\treturn;'''
    new = '''\t// Missing loop body (0x825CD474-0x825CD678) was not generated by codegen.\n\t// The original code loops back to 0x825CD3F0 and then enters the epilogue\n\t// at 0x825CD678. Bypass the broken split and call the epilogue directly.\n\tsub_825CD678(ctx, base);\n\treturn;'''
    if old in txt:
        txt = txt.replace(old, new)
        file_path.write_text(txt, encoding="utf-8")
        print("patched sub_825CD3C0 bypass")
    else:
        print("sub_825CD3C0 already patched or no longer matches")

if __name__ == "__main__":
    root = pathlib.Path(__file__).parent.parent
    patch_sub_825cd3c0(root / "generated" / "default" / "xmd_recomp.139.cpp")
